### ISSUE TITLE
Embroider support

### ISSUE THREAD

**Issue by joelcox** [sinankeskin/ember-dayjs#103]
Thanks for creating this drop-in replacement for moment? Been looking to move away.

Is something like [adding Embroider support](https://github.com/embroider-build/embroider/tree/master/packages/test-setup) on the roadmap?

**Comment by sinankeskin** [comment]
Definitely. I'm trying to create free time. Hopefully soon I'll add Embroider support to all my addons not just this.

Thanks.

**Comment by sinankeskin** [comment]
Hi @joelcox 

Could you please try v0.3.0? I believe it should work with Embroider now.

Thanks.

**Comment by joelcox** [comment]
@sinankeskin That was fast! This seemed to have fixed this issues with missing imports, but I think it still causes issues when using `ember build --environment=production`.

```
Uncaught Error: an unsupported module was defined, expected `define(id, deps, module)` instead got: `1` arguments to define`
    at a (loader.js:58)
    at define (loader.js:197)
    at Object.3012 (chunk.a95bd5ad60f0d54ef9a1.js:formatted:710)
    at a (chunk.448dfe2932974e809734.js:1)
    at Object.69151 (chunk.448dfe2932974e809734.js:1)
    at a (chunk.448dfe2932974e809734.js:1)
    at Object.50539 (chunk.448dfe2932974e809734.js:1)
    at a (chunk.448dfe2932974e809734.js:1)
    at s.callback (chunk.448dfe2932974e809734.js:1)
    at s.exports (loader.js:106)
```


```
 "object" == ("undefined" == typeof exports ? "undefined" : (0,
        o.Z)(exports)) ? e.exports = i() : "function" == typeof define && n.amdO ? define(i) : (r = "undefined" != typeof globalThis ? globalThis : r || self).dayjs = I()
```

Hoping to dig in later this week and let you know!

**Comment by joelcox** [comment]
@sinankeskin I had a long hard look but wasn't really able to figure did out. Tried to infer what might be going wrong from other Embroider ready dependencies, but no luck. Turned out we really weren't using helpers in this project, so we just directly imported moment with `ember-auto-loader`. This might become relevant again at a later point in time when we end up porting other apps.

**Comment by sinankeskin** [comment]
You mean dayjs but I got your point. Thanks.

**Comment by joelcox** [comment]
Yup, sorry about that

> imported days with `ember-auto-loader`

**Comment by joelcox** [comment]
Thanks for letting me know. I removed this library as a dependency for now, but probably to use this suggestion on another project we plan on migrating in Q4 or Q1!

**Comment by sinankeskin** [comment]
Closing. Works with embroider perfectly now.

Please feel free to re-open if you see any other issues.

Thanks @joelcox

**Comment by joelcox** [comment]
Thanks, looking forward using this in the next project!
