### ISSUE TITLE
dayjs-format usage

### ISSUE THREAD

**Issue by vst** [sinankeskin/ember-dayjs#122]
README states that the `dayjs-format` usage is:

```hbs
{{dayjs-format <date> [outputFormat=dayjs.defaultFormat]}}
```

... and the example is given as:

```hbs
{{dayjs-format '12-1995-25' 'MM/DD/YYYY'}} {{!-- 25/12/1995 --}}
```

However, this did not work for me. I had to add the `outputFormat` keyword argument.

Without `outputFormat` keyword argument:

```hbs
{{dayjs-format "2021-12-31" "DD/MM/YYYY"}}  {{! 2021-12-31T00:00:00+08:00 }}
```

With `outputFormat` keyword argument:

```hbs
{{dayjs-format "2021-12-31" outputFormat="DD/MM/YYYY"}}  {{! 31/12/2021 }}
```

I used to use the former one with `ember-moment`.

Am I missing something?

**Comment by sinankeskin** [comment]
You are right @vst I must have missed this.

I'll fix ASAP. If you see any other inconsistencies please report.

Thanks.

**Comment by vst** [comment]
No problem. Thanks for this addon and your effort!

**Comment by sinankeskin** [comment]
I've released [0.4.0](https://www.npmjs.com/package/ember-dayjs) @vst It should be fixed now.

Could you please try?

Thanks.

**Comment by vst** [comment]
Thanks a lot, @sinankeskin. I will, but I need 1 or 2 days.

**Comment by vst** [comment]
@sinankeskin Sorry for the delay.

It works as expected. Thanks! :+1:
