### ISSUE TITLE
Using locale in helper

### ISSUE THREAD

**Issue by YaroslavPoliakov** [sinankeskin/ember-dayjs#253]
Hey, first of all thank you for this addon! It's very convenient and useful.
Unfortunately, I'm stumbled upon the issue with the next code:
`{{dayjs-from-now @comment.posted locale='ru'}}`
I do have this locale in a ember-cli-build.js:
```
    'ember-dayjs': {
      locales: ['ru'],
      plugins: ['utc', 'relativeTime'],
    }
```
However the string appears in English. How can I change to other locale?
P.S. I've tried to call 'setLocale' in ApplicationController - didn't have any effect.

**Comment by sinankeskin** [comment]
Hey @YaroslavPoliakov You just need set locale via `dayjs` service `setLocale` method like here. You can check the dummy app in the addon.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/2091777/163861486-51beb970-57d8-4341-98e0-d22a89ffeb27.png">


<img width="238" alt="image" src="https://user-images.githubusercontent.com/2091777/163861446-c61b8ed0-7954-49c8-9ffc-15cf3bebaebb.png">

**Comment by YaroslavPoliakov** [comment]
I've tried to set in a ApplicationController constructor - no effect. It's called and returns no errors. However the helper is still in English.
```
export default class ApplicationController extends Controller {
  @service dayjs;

  constructor(owner, args) {
    super(owner, args);
    this.dayjs.setLocale('ru');
  }
```

**Comment by sinankeskin** [comment]
> I've tried to set in a ApplicationController constructor - no effect. It's called and returns no errors. However the helper is still in English.
> 
> ```
> export default class ApplicationController extends Controller {
>   @service dayjs;
> 
>   constructor(owner, args) {
>     super(owner, args);
>     this.dayjs.setLocale('ru');
>   }
> ```
> 
> UPD: Looks like I luckily bumped into one helper that doesn't work properly 😅 . I've checked the ones from a dummy app, and indeed they work as intended.

Yeap. Not all helpers works with multiple locales. Maybe I should to add to doc which helpers works. Thanks for the heads up @YaroslavPoliakov

**Comment by YaroslavPoliakov** [comment]
So I've ended up with changing from
`{{dayjs-from-now @comment.posted locale='ru'}}`
to
`{{dayjs-to (now) @comment.posted}}`
and also adding a `setLocale('ru')` call because it looks like the `locale` parameter doesn't work with this helper. And it did a trick :) Thank you for your help!
