### ISSUE TITLE
dayjs-duration-humanize missing plugin in helpers

### ISSUE THREAD

**Issue by xav-car** [sinankeskin/ember-dayjs#343]
Hi,

i'm trying ti use `dayjs-duration-humanize` inside an app. it seem to missing 

`{{dayjs-duration-humanize tutorial.duration "minutes"}}`

i've got this error

```
duration.js:1 Uncaught (in promise) TypeError: t(...).add(...).locale(...).fromNow is not a function
    at y.humanize (duration.js:1:1)
    at DayjsDurationHumanize.compute (dayjs-duration-humanize.js:12:1)
    at index.js:5036:24
    at deprecateMutationsInTrackingTransaction (validator.js:142:7)
    at ClassicHelperManager.getValue (index.js:5035:7)
    at manager.js:847:52
    at reference.js:121:35
    at track (validator.js:709:5)
    at valueForRef (reference.js:120:21)
    at Object.evaluate (runtime.js:3777:31)

```

i 've added     `this.dayjs.extend('relativeTime');`  just before super in order to work.
```
import DayjsDurationHelper from './dayjs-duration';

export default class DayjsDurationHumanize extends DayjsDurationHelper {
  compute(params, hash) {
    this.dayjs.useLocale(hash.locale || this.dayjs.locale);
    this.dayjs.extend('relativeTime');

    return super
      .compute(params, hash)
      .locale(hash.locale || this.dayjs.locale)
      .humanize();
  }
}
```

**Comment by sinankeskin** [comment]
You are right. Looks like either I forgot to add or document was missing at that time. I'll fix ASAP. Thank you @xav-car for reporting.

**Comment by xav-car** [comment]
i saw this to. ember-dayjs instancitate locale only for him. it doesn't set locale pour dayjs library ? is it the good behavior ? 

for the moment i set locale with days.self.locale(<myLocale>)

**Comment by sinankeskin** [comment]
Fixed now. Please use v0.10.0. Thanks.

**Comment by sinankeskin** [comment]
> i saw this to. ember-dayjs instancitate locale only for him. it doesn't set locale pour dayjs library ? is it the good behavior ?
> 
> for the moment i set locale with days.self.locale()

Sorry missed this. That's totally fine. I don't set locale for dayjs library globally.

Closing this. Feel free to reopen if you see anything else.

Thanks for report @xav-car
