### ISSUE TITLE
Unix helper not multiplying values by 1000

### ISSUE THREAD

**Issue by jeffdaley** [sinankeskin/ember-dayjs#389]
I'm having trouble with the `{{unix}}` helper.

In the docs, the example shows

```
{{unix 1516586508}}
{{! Sun Jan 21 2018 21:01:48 GMT-0500 }}
```

But I get a different result:

```
{{unix 1516586508}}
{{! Sun, 18 Jan 1970 13:16:26 GMT }}
```

It's only until I multiply the input by 1000 that I get the desired output:

```
{{unix (multiply 1000 1516586508)}}
{{! Mon, 22 Jan 2018 02:01:48 GMT }}
```

Is there something I'm doing wrong?

**Comment by sinankeskin** [comment]
Let me check @jeffdaley Thanks for reporting.

**Comment by sinankeskin** [comment]
As [document](https://day.js.org/docs/en/display/unix-timestamp-milliseconds#docsNav) states here we're assuming the time is milliseconds not the seconds. I took most of the docs from the ember-moment repo. This is simply a document issue.

I've just checked and helper works just fine. If you wanna use seconds unix time what you're doing is perfectly fine. Simple multiple by 1000.

I'll update docs in a minute. Thank you @jeffdaley

**Comment by jeffdaley** [comment]
Thanks Sinan

**Comment by jeffdaley** [comment]
After looking at the Day.js docs some more, I think my assumption of a seconds-based `{{unix}}` helper might be right.

[The page you linked](https://day.js.org/docs/en/display/unix-timestamp-milliseconds) uses the `valueOf` function to generate a millisecond value:

```
dayjs('2019-01-25').valueOf() // 1548381600000
```

whereas the [`unix()` function](https://day.js.org/docs/en/display/unix-timestamp) outputs in seconds:
```
dayjs('2019-01-25').unix() // 1548381600
```

Given that `unix()` generates a 10-digital value, I'd expect the `{{unix}}` helper to do the same, in reverse.

**Comment by sinankeskin** [comment]
I'm not using the valueOf method there. I'm using the 2nd way of using constructor in that document @jeffdaley which is the cheapest.

https://github.com/sinankeskin/ember-dayjs/blob/main/addon/helpers/unix.js

**Comment by jeffdaley** [comment]
Gotcha, thanks for clarifying, and for your help overall. Much appreciated! 🙌
