### ISSUE TITLE
Unclear how to UpdateLocale

### ISSUE THREAD

**Issue by jeffdaley** [sinankeskin/ember-dayjs#390]
I'm hoping to use the [`UpdateLocale`](https://day.js.org/docs/en/plugin/update-locale) plugin to tweak the English `relativeTime` labels as [described in the Day.js docs](https://day.js.org/docs/en/customization/relative-time)

I added the plugin to my `ember-cli-build` config, expecting it to affect the injected service, e.g.,

```
@service dayjs;

beforeModel() {
  this.day.js.updateLocale('en', {
    relativeTime: { d: "yesterday"}
  })
}
```

but the plugin doesn't seem to affect the service, i.e., `this.dayjs.updateLocale` is undefined.

I'm probably approaching this wrong. How do I make these types of global changes to the config?

**Comment by sinankeskin** [comment]
Just make sure you added plugin correctly first.

It should be like this in `ember-cli-build.js`:

```js
'ember-dayjs': {
   plugins: ['updateLocale'], // Case-sensitive
},
```


and after that you need to use like:

```js
this.dayjs.extend('updateLocale');
this.dayjs.updateLocale('en', {
  relativeTime: { d: "yesterday"}
});
```

@jeffdaley 

Feel free to reach me any possible further questions.

**Comment by jeffdaley** [comment]
Thanks again. Unfortunately this isn't working for me:

`ember-cli-build`:

```
    "ember-dayjs": {
      plugins: ["relativeTime", "updateLocale"],
    },
```

`routes/application.js`
```
@service dayjs;

 async beforeModel() {
    this.dayjs.extend("updateLocale");
    this.dayjs.updateLocale() 
}
```

**Comment by sinankeskin** [comment]
Ok tomorrow I'll check thoroughly get back to you Jeff with a result. Thanks.

**Comment by sinankeskin** [comment]
Oh I just checked the code. I've made mistake. Final part should be like this:

```js
this.dayjs.extend('updateLocale');
this.dayjs.self.updateLocale('en', {
  relativeTime: { d: "yesterday"}
});
```

Notice the `self` part.

Could you please try @jeffdaley? This should work I believe.

**Comment by jeffdaley** [comment]
@sinankeskin Indeed, the `self` is necessary; thank you for tracking that down.

Since `updateLocale` also depends on `relativeTime` I learned that I also need to extend that plugin.

Final working code:

```
    this.dayjs.extend("relativeTime");
    this.dayjs.extend("updateLocale");
    this.dayjs.self.updateLocale("en", {
      relativeTime: {
          ...
     }
  }
```
