### ISSUE TITLE
Instantiate globally dayjs

### ISSUE THREAD

**Issue by xav-car** [sinankeskin/ember-dayjs#451]
Hello, first of all thanks for your work.

We have a question. 

It seems dayjs locale aren't set globally when we do : `this.days.setLocale('fr')` . We have to do `this.dayjs.self.locale('fr')`.
We saw this thrick when we use dayjs chartjs adapter in order to display the right language https://github.com/1024pix/pix/pull/6285 .

This is the way of ember-dayjs ? Or can we set dayjs locale when we define the  `this.days.setLocale('fr')` ?

Thanks !

**Comment by sinankeskin** [comment]
I'm setting the locale globally here: https://github.com/sinankeskin/ember-dayjs/blob/1138c3e001e733de64e6146c18eb92a617aed6c7/ember-dayjs/src/services/dayjs.js#L18

So after you call `this.days.setLocale('fr')` language should be French for every helper but either that's my mistake or dayjs changed the behavior because I'm seeing [this](https://day.js.org/docs/en/i18n/changing-locale) after your message here.

I'll update in a minute. Thanks @xav-car

**Comment by sinankeskin** [comment]
Ok I just checked the code and my approach was not to set locale globally instead using locale locally for whenever needed as documented [here](https://day.js.org/docs/en/i18n/instance-locale).

Like this: https://github.com/sinankeskin/ember-dayjs/blob/1138c3e001e733de64e6146c18eb92a617aed6c7/ember-dayjs/src/helpers/dayjs-duration-humanize.js#L10

What's your issue exactly? Not all helpers support locale. What are you trying to achieve? @xav-car

**Comment by xav-car** [comment]
We use [dayjs adapter for chartjs](https://github.com/bolstycjw/chartjs-adapter-dayjs-4), until we set `this.dayjs.self.locale` to fr, the charts still display in english whereas we define `this.dayjs.setLocale` to `fr`.

Chartjs use the global instance of dayjs so we need to have the language inside dayjs.

is it possible to set dayjs language inside ember dayjs instead to define two time the language [example here](https://github.com/1024pix/pix/pull/6285/files#diff-af98be297808f8657920a437d4587fa397889ea8e16a82deea9189521f4136c3)?

**Comment by sinankeskin** [comment]
Now I understood the issue perfectly. That package depends on the global dayjs object but I don't set globally. This will be a behavioral change but I'll set the locale globally and I'll remove locale field from service. This will solve your problem. I'll ping you just a couple minute later. Thanks @xav-car

**Comment by sinankeskin** [comment]
I've just released ember-dayjs@0.12.0 @xav-car Please check. This should solve your problem.

**Comment by xav-car** [comment]
it works fine. thanks a lot for your reactivity

**Comment by sinankeskin** [comment]
You are always welcome. My pleasure.

**Comment by bartocc** [comment]
hey @sinankeskin.

I do not see the 0.12.0 tag in the repo for this new release.
Could you please add it for better readability of the project?

Thx

**Comment by sinankeskin** [comment]
Hey @bartocc 👋🏻

I must have missed it. I'll add asap.

**Comment by sinankeskin** [comment]
Done. Thanks for the heads up.
